In [ ]:
#kidney disease prediction application
#import tools
import numpy as np
import pandas as pd

#preprocesing tools
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split

#classification models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier

#for model evaluation
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
#load data
df=pd.read_csv("/content/drive/MyDrive/dataset/kidney_disease.csv")

filtered_df = df[df["classification"] != "ckd"]

df.head(100)

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,62.0,90.0,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,...,NaN,NaN,NaN,yes,no,no,good,yes,yes,ckd
96,96,60.0,80.0,1.010,1.0,1.0,NaN,normal,notpresent,notpresent,...,36,NaN,NaN,no,yes,yes,poor,no,no,ckd
97,97,65.0,60.0,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,...,32,9100,4.0,yes,yes,no,poor,yes,no,ckd
98,98,50.0,140.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,...,18,5800,2.3,yes,yes,no,poor,no,yes,ckd
99,99,56.0,180.0,NaN,0.0,4.0,NaN,abnormal,notpresent,notpresent,...,32,10400,4.2,yes,yes,no,poor,yes,no,ckd

In [ ]:
important_columns=['age','bp','sg','al','hemo','pcv','rc','bu','bgr','sc','sod','pot','htn','dm','cad','appet','pc','pe','ane','classification']
df=df[important_columns]
df.head(200)

,age,bp,sg,al,hemo,pcv,rc,bu,bgr,sc,sod,pot,htn,dm,cad,appet,pc,pe,ane,classification
0,48.0,80.0,1.020,1.0,15.4,44,5.2,36.0,121.0,1.2,NaN,NaN,yes,yes,no,good,normal,no,no,ckd
1,7.0,50.0,1.020,4.0,11.3,38,NaN,18.0,NaN,0.8,NaN,NaN,no,no,no,good,normal,no,no,ckd
2,62.0,80.0,1.010,2.0,9.6,31,NaN,53.0,423.0,1.8,NaN,NaN,no,yes,no,poor,normal,no,yes,ckd
3,48.0,70.0,1.005,4.0,11.2,32,3.9,56.0,117.0,3.8,111.0,2.5,yes,no,no,poor,abnormal,yes,yes,ckd
4,51.0,80.0,1.010,2.0,11.6,35,4.6,26.0,106.0,1.4,NaN,NaN,no,no,no,good,normal,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,70.0,90.0,1.020,2.0,5.8,NaN,NaN,98.6,184.0,3.3,138.0,3.9,yes,yes,yes,poor,abnormal,no,no,ckd
196,49.0,100.0,1.010,3.0,8.1,24,3.5,158.0,129.0,11.8,122.0,3.2,yes,yes,no,poor,abnormal,yes,yes,ckd
197,57.0,80.0,NaN,NaN,6.8,NaN,3.0,111.0,NaN,9.3,124.0,5.3,yes,yes,no,good,NaN,no,yes,ckd
198,59.0,100.0,1.020,4.0,11.2,30,3.9,40.0,252.0,3.2,137.0,4.7,yes,yes,no,poor,normal,yes,no,ckd
199,65.0,80.0,1.015,0.0,8.8,25,3.2,37.0,92.0,1.5,140.0,5.2,yes,no,yes,good,normal,yes,no,ckd

In [ ]:
# data preprocessing
# 1. remove \t from all values
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.replace('\t', '', regex=True)

In [ ]:
#2. check isnull
df.isnull().sum()

age                 0
bp                  0
sg                  0
al                  0
hemo                0
pcv                70
rc                130
bu                 19
bgr                44
sc                 17
sod                87
pot                88
htn                 2
dm                  2
cad                 2
appet               1
pc                 65
pe                  1
ane                 1
classification      0
dtype: int64

In [ ]:
import numpy as np
#3  fill missing values
# Convert 'pcv' and 'rc' to numeric, coercing errors to NaN
df['pcv'] = pd.to_numeric(df['pcv'], errors='coerce')
df['rc'] = pd.to_numeric(df['rc'], errors='coerce')

df['age'] = df['age'].fillna(df['age'].median())
df['bp'] = df['bp'].fillna(df['bp'].median())
df['sg'] = df['sg'].fillna(df['sg'].median())
df['al'] = df['al'].fillna(df['al'].median())
df['hemo'] = df['hemo'].fillna(df['hemo'].median())
df['pcv'] = df['pcv'].fillna(df['pcv'].median())
df['rc'] = df['rc'].fillna(df['rc'].median())
df['bu'] = df['bu'].fillna(df['bu'].median())
df['bgr'] = df['bgr'].fillna(df['bgr'].median())
df['sc'] = df['sc'].fillna(df['sc'].median())
df['sod'] = df['sod'].fillna(df['sod'].median())
df['pot'] = df['pot'].fillna(df['pot'].median())
df['htn'] = df['htn'].fillna(df['htn'].mode()[0])
df['dm'] = df['dm'].fillna(df['dm'].mode()[0])
df['cad'] = df['cad'].fillna(df['cad'].mode()[0])
df['appet'] = df['appet'].fillna(df['appet'].mode()[0])
df['pc'] = df['pc'].fillna(df['pc'].mode()[0])
df['pe'] = df['pe'].fillna(df['pe'].mode()[0])
df['ane'] = df['ane'].fillna(df['ane'].mode()[0])
df['classification'] = df['classification'].fillna(df['classification'].mode()[0])
df.isnull().sum()
#df.head()

age               0
bp                0
sg                0
al                0
hemo              0
pcv               0
rc                0
bu                0
bgr               0
sc                0
sod               0
pot               0
htn               0
dm                0
cad               0
appet             0
pc                0
pe                0
ane               0
classification    0
dtype: int64

In [ ]:
# lable encoding categorical values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['htn'] = le.fit_transform(df['htn'])
df['dm'] = le.fit_transform(df['dm'])
df['cad'] = le.fit_transform(df['cad'])
df['classification'] = le.fit_transform(df['classification'])
df['appet'] = le.fit_transform(df['appet'])
df['pc'] = le.fit_transform(df['pc'])
df['pe'] = le.fit_transform(df['pe'])
df['ane'] = le.fit_transform(df['ane'])
df.head(200)

,age,bp,sg,al,hemo,pcv,rc,bu,bgr,sc,sod,pot,htn,dm,cad,appet,pc,pe,ane,classification
0,0.522727,0.230769,0.75,0.2,0.836735,0.777778,0.525424,0.088575,0.211538,0.010582,0.842271,0.042697,1,1,0,0,1,0,0,0
1,0.056818,0.000000,0.75,0.8,0.557823,0.644444,0.457627,0.042362,0.211538,0.005291,0.842271,0.042697,0,0,0,0,1,0,0,0
2,0.681818,0.230769,0.25,0.4,0.442177,0.488889,0.457627,0.132221,0.856838,0.018519,0.842271,0.042697,0,1,0,1,1,0,1,0
3,0.522727,0.153846,0.00,0.8,0.551020,0.511111,0.305085,0.139923,0.202991,0.044974,0.671924,0.000000,1,0,0,1,0,1,1,0
4,0.556818,0.230769,0.25,0.4,0.578231,0.577778,0.423729,0.062901,0.179487,0.013228,0.842271,0.042697,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.772727,0.307692,0.75,0.4,0.183673,0.688889,0.457627,0.249294,0.346154,0.038360,0.842271,0.031461,1,1,1,1,0,0,0,0
196,0.534091,0.384615,0.25,0.6,0.340136,0.333333,0.237288,0.401797,0.228632,0.150794,0.741325,0.015730,1,1,0,1,0,1,1,0
197,0.625000,0.230769,0.75,0.0,0.251701,0.688889,0.152542,0.281130,0.211538,0.117725,0.753943,0.062921,1,1,0,0,1,0,1,0
198,0.647727,0.384615,0.75,0.8,0.551020,0.466667,0.305085,0.098845,0.491453,0.037037,0.835962,0.049438,1,1,0,1,1,1,0,0
199,0.715909,0.230769,0.50,0.0,0.387755,0.355556,0.186441,0.091142,0.149573,0.014550,0.854890,0.060674,1,0,1,0,1,1,0,0

In [ ]:
# scalling the data
numerical_columns=['age','bp','sg','al','hemo','pcv','rc','bu','bgr','sc','sod','pot']

scaler=MinMaxScaler()
df[numerical_columns]=scaler.fit_transform(df[numerical_columns])
df

,age,bp,sg,al,hemo,pcv,rc,bu,bgr,sc,sod,pot,htn,dm,cad,appet,pc,pe,ane,classification
0,0.522727,0.230769,0.75,0.2,0.836735,0.777778,0.525424,0.088575,0.211538,0.010582,0.842271,0.042697,1,1,0,0,1,0,0,0
1,0.056818,0.000000,0.75,0.8,0.557823,0.644444,0.457627,0.042362,0.211538,0.005291,0.842271,0.042697,0,0,0,0,1,0,0,0
2,0.681818,0.230769,0.25,0.4,0.442177,0.488889,0.457627,0.132221,0.856838,0.018519,0.842271,0.042697,0,1,0,1,1,0,1,0
3,0.522727,0.153846,0.00,0.8,0.551020,0.511111,0.305085,0.139923,0.202991,0.044974,0.671924,0.000000,1,0,0,1,0,1,1,0
4,0.556818,0.230769,0.25,0.4,0.578231,0.577778,0.423729,0.062901,0.179487,0.013228,0.842271,0.042697,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.602273,0.230769,0.75,0.0,0.857143,0.844444,0.474576,0.121951,0.252137,0.001323,0.917981,0.053933,0,0,0,0,1,0,0,1
396,0.454545,0.153846,1.00,0.0,0.911565,1.000000,0.694915,0.075738,0.113248,0.010582,0.861199,0.022472,0,0,0,0,1,0,0,1
397,0.113636,0.230769,0.75,0.0,0.863946,0.888889,0.559322,0.062901,0.166667,0.002646,0.835962,0.042697,0,0,0,0,1,0,0,1
398,0.170455,0.076923,1.00,0.0,0.755102,0.933333,0.644068,0.124519,0.196581,0.007937,0.823344,0.053933,0,0,0,0,1,0,0,1
399,0.636364,0.230769,1.00,0.0,0.863946,0.977778,0.677966,0.042362,0.232906,0.009259,0.861199,0.022472,0,0,0,0,1,0,0,1

In [ ]:
#balance the data for target value
df['classification'].value_counts()
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=42)
X=df.drop('classification',axis=1)
y=df['classification']

X_balanced,y_balanced=smote.fit_resample(X,y)
y_balanced.value_counts()

classification
0    250
1    250
Name: count, dtype: int64

In [ ]:
# split test and train
X_train,X_test,y_train,y_test=train_test_split(X_balanced,y_balanced,test_size=0.2,random_state=42)

#check the shape
print(X_train.shape,X_test.shape)

(400, 19) (100, 19)

In [ ]:
# train multiple classfication models
models = {
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Support Vector Machine': SVC(),
    'Naive Bayes': GaussianNB(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'AdaBoost': AdaBoostClassifier()
}

# train and evaluate each model
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)

    # Print the results
    print(f"Model: {name}")
    print(f"Accuracy: {accuracy}")
    print("Confusion Matrix:")
    print(conf_matrix)
    print("Classification Report:")
    print(class_report)
    print("="*50)

Model: Logistic Regression
Accuracy: 0.95
Confusion Matrix:
[[41  5]
 [ 0 54]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.89      0.94        46
           1       0.92      1.00      0.96        54

    accuracy                           0.95       100
   macro avg       0.96      0.95      0.95       100
weighted avg       0.95      0.95      0.95       100

==================================================
Model: Decision Tree
Accuracy: 0.99
Confusion Matrix:
[[45  1]
 [ 0 54]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        46
           1       0.98      1.00      0.99        54

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

==================================================
Model: K-Nearest Neighbors
Accuracy: 0.97
Confusion Matrix:
[[43  3]
 [ 0 54]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        46
           1       0.95      1.00      0.97        54

    accuracy                           0.97       100
   macro avg       0.97      0.97      0.97       100
weighted avg       0.97      0.97      0.97       100

==================================================
Model: Support Vector Machine
Accuracy: 0.97
Confusion Matrix:
[[43  3]
 [ 0 54]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        46
           1       0.95      1.00      0.97        54

    accuracy                           0.97       100
   macro avg       0.97      0.97      0.97       100
weighted avg       0.97      0.97      0.97       100

==================================================
Model: Naive Bayes
Accuracy: 0.96
Confusion Matrix:
[[42  4]
 [ 0 54]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95        46
           1       0.93      1.00      0.96        54

    accuracy                           0.96       100
   macro avg       0.97      0.96      0.96       100
weighted avg       0.96      0.96      0.96       100

==================================================
Model: Gradient Boosting
Accuracy: 0.99
Confusion Matrix:
[[45  1]
 [ 0 54]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        46
           1       0.98      1.00      0.99        54

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

==================================================
Model: AdaBoost
Accuracy: 0.99
Confusion Matrix:
[[45  1]
 [ 0 54]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        46
           1       0.98      1.00      0.99        54

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

==================================================

In [ ]:
#selecting best model

model_gbc= GradientBoostingClassifier()
model_gbc.fit(X_train,y_train)
y_pred=model_gbc.predict(X_test)
print(confusion_matrix(y_test,y_pred))

[[45  1]
 [ 0 54]]

In [ ]:
#saving model, scaller for production
import pickle
pickle.dump(model_gbc,open('/content/drive/MyDrive/Models/model-kidney-disease.pkl','wb'))
pickle.dump(scaler,open('/content/drive/MyDrive/Models/scaller-kidney-disease.pkl','wb'))

In [ ]:

#load the model and scaller
model=pickle.load(open('/content/drive/MyDrive/Models/model-kidney-disease.pkl','rb'))
scaller=pickle.load(open('/content/drive/MyDrive/Models/scaller-kidney-disease.pkl','rb'))

#Prediction on new data using function
#def predict_kidney_disease(age, bp, sg, al, hemo, sc,sod,pot, htn, dm, cad, appet, pc,pe):
def predict_kidney_disease(age, bp, sg, al, hemo,pcv,rc,bu,bgr, sc,sod,pot, htn, dm, cad, appet, pc,pe,ane):
    # Create a DataFrame with input variables, following the correct order
    df_dict = {
        'age': [age],
        'bp': [bp],
        'sg': [sg],
        'al': [al],
        'hemo': [hemo],
        'pcv': [pcv],
        'rc': [rc],
        'bu': [bu],
        'bgr': [bgr],
        'sc': [sc],
        'sod':[sod],
        'pot':[pot],
        'htn': [htn],
        'dm': [dm],
        'cad': [cad],
        'appet': [appet],
        'pc': [pc],
        'pe' : [pe],
        'ane': [ane]
    }
    df = pd.DataFrame(df_dict)

    # Encode the categorical columns
    le = LabelEncoder()
    df['htn'] = le.fit_transform(df['htn'])
    df['dm'] = le.fit_transform(df['dm'])
    df['cad'] = le.fit_transform(df['cad'])
    df['appet'] = le.fit_transform(df['appet'])
    df['pc'] = le.fit_transform(df['pc'])
    df['pe'] = le.fit_transform(df['pe'])
    df['ane'] =le.fit_transform(df['ane'])

    # Scale the numeric columns using the previously fitted scaler
    numeric_cols=['age','bp','sg','al','hemo','pcv','rc','bu','bgr','sc','sod','pot']
    df[numeric_cols] = scaller.transform(df[numeric_cols])

    # Make the prediction
    prediction = model.predict(df)

    # Return the predicted class
    return prediction[0]

In [ ]:
#predict the results now giving varable values
#ckd sample data:
#   62.0	80.0	1.010	2.0	9.6	    1.8 138.0	4.4	no	yes	no	poor	normal	    ckd
#	48.0	70.0	1.005	4.0	11.2	3.8	138.0	4.4 yes	no	no	poor	abnormal	ckd
#---------No CKD----------
#	55.0	80.0	1.020	0.0	15.7	0.5	no	no	no	good	normal	notckd
#	42.0	70.0	1.025	0.0	16.5	1.2	no	no	no	good	normal	notckd
input_data = {
    'age': 25,          # 1.Age in years (older age is associated with a higher risk of CKD)
    'bp': 80,           # 2.Blood pressure in mmHg (high blood pressure is a major risk factor)
    'sg': 1.020,        # 3.Urine specific gravity (low or abnormal values may indicate impaired kidney function)
    'al': 0.0,          # 4.Urine albumin level (protein in urine; elevated levels suggest kidney damage)
    'hemo': 15.4,       # 5.Hemoglobin level in g/dL (low levels may indicate anemia, common in CKD)
    'pcv'  :44.0,       # 6.Packed Cell Volume (PCV)
    'rc' : 5.2,         # 7.Red Blood Cell Count (RBC)
    'bu': 36.0,         # 8.Blood Urea
    'bgr': 121.0,       # 9.Random Blood Glucose
    'sc': 0.5,          # 10.Serum creatinine in mg/dL (higher values indicate reduced kidney function)
    'sod':100.0,        # 11. Sodium
    'pot':4.5,          # 12. Potassium
    'htn': 'no',        # 13.Hypertension ('yes' if the patient has high blood pressure)
    'dm': 'no',         # 14.Diabetes mellitus ('yes' if the patient has diabetes, a major CKD risk factor)
    'cad': 'no',        # 15.Coronary artery disease ('yes' if the patient has heart disease)
    'appet': 'good',    # 16.Appetite ('good' or 'poor'; poor appetite is common in advanced CKD)
    'pc': 'normal',     # 17.Pus cells in urine ('normal' or 'abnormal'; abnormal may indicate infection or inflammation)
    'pe': 'no ',        # 18.Yes may indicate kidney desease
    'ane': 'no',        # 19. aanemia
}
result = predict_kidney_disease(**input_data)
if result == 0: # 0 represents 'ckd' based on label encoding
    print("Patient has kidney disease")
else:
  print("Patient does not have kidney disease")

Patient does not have kidney disease

In [ ]:
import sklearn
print(sklearn.__version__)

1.6.1

In [ ]:
# check python version
import sys
print(sys.version)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]